Add Upgrade Test cases for sys and ISC views
amazon-aurora/babelfish_extensions pull request #30
Opened 2022-11-15 07:38 UTC by shah-nirmit

Signed-off-by: Nirmit Shah <nirmisha@amazon.com>

2022-11-16 12:39 UTC, Deepesh125 requested changes

2022-11-17 04:22 UTC, shah-nirmit commented on test/JDBC/input/ISC-Columns-vu-prepare.sql
> +
We use the db created to check the output of information_schema.columns in the newly created db
```
USE isc_columns_db1
GO

--should return nothing
SELECT * FROM information_schema.columns WHERE TABLE_NAME != 'sysdatabases'
SELECT * FROM information_schema.columns WHERE TABLE_NAME != 'SYSDATABASES'
GO

USE master
GO
```

2022-11-17 05:32 UTC, shah-nirmit commented on test/JDBC/upgrade/13_7/schedule
> -BABEL-SP_FKEYS
Fixed in latest commit

2022-11-17 08:37 UTC, Deepesh125 approved these changes

2022-11-17 08:37 UTC, merged