Support dbcreator fixed server role
amazon-aurora/babelfish_extensions pull request #65
Opened 2024-09-11 08:06 UTC by anju15bharti

*Issue #, if available:*
BABEL-5115

*Description of changes:*
Added support for new fixed server role dbcreator

This role has following privileges with it:
Members of the dbcreator fixed server role can create, alter, drop database. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-09-20 10:50 UTC, HarshLunagariya commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +							|| roleid == dbcreator_oid))
We will need to refactor this. Given that we will be introducing around 5-6 roles in the future.

2024-09-20 10:50 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/catalog.c
> +		&& !(user && has_privs_of_role(GetSessionUserId(), get_dbcreator_oid())))
Can you please explain this?

2024-09-20 10:50 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +						/* If grantee role is member of sysadmin then don't revoke createdb */
misleading comment

2024-10-16 05:41 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/catalog.c
> +		&& !(user && has_privs_of_role(GetSessionUserId(), get_dbcreator_oid())))
For a login which is member of dbcreator want to alter database name then it should have access to that database(which it can have if there is a mapped user for that login in that database).

2024-10-17 08:57 UTC, tanscorpio7 requested changes

2024-10-17 08:57 UTC, tanscorpio7 commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +	dbcreator_oid = get_role_oid(BABELFISH_DBCREATOR, false);
Can we cache these OIDs in this file.

2024-10-17 08:57 UTC, tanscorpio7 commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +							|| roleid == dbcreator_oid))
Curious why sysadmin is not inlcuded here ?

2024-10-17 08:57 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/sql/ownership.sql
> +	EXECUTE format('GRANT CONNECT ON DATABASE %s TO dbcreator WITH GRANT OPTION', CURRENT_DATABASE());
I think we discussed this in `Securityadmin` PR that we do not need this.

2024-10-17 08:57 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--4.3.0--4.4.0.sql
> +
This will be a common function for securityadmin and db_creator right ?

2024-10-17 08:57 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/backend_parser/gram-tsql-epilogue.y.c
> +							&& strcmp(serverrole, BABELFISH_DBCREATOR) != 0)
Lets create a MACRO for this.

2024-10-17 08:57 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/catalog.c
> +	user = get_user_for_database(old_db_name);
Should we put it inside the if condition, only compute this if not member of sysadmin. Not a performance critical path but good to have.

2024-10-17 08:57 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							appendStringInfo(&query, "ALTER ROLE dummy WITH nocreaterole; ");
I think this entire code block should be refactored into another function.

We first figure out through how many server role membership is a particular attribute granted to current role and only revoke that attribute if count is one.

2024-10-17 08:57 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/sql/ownership.sql
> +	EXECUTE format('GRANT CONNECT ON DATABASE %s TO dbcreator WITH GRANT OPTION', CURRENT_DATABASE());
Also do we need to give `dbcreator` any permission from PG perspective ? Members of this role are again granted this attribute and this role will never be the session user. Same goes for securityadmin.

2024-10-17 08:58 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/catalog.c
> +		&& !(user && has_privs_of_role(GetSessionUserId(), get_dbcreator_oid())))
Do we have a test case where dbcreator has a user but it is disabled ?

2024-10-17 17:10 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/catalog.c
> +		&& !(user && has_privs_of_role(GetSessionUserId(), get_dbcreator_oid())))
We can only disable login not user but yes to check this scenario by revoking connect from user for that db which will basically mean that there is no user for that db leading to fall into this case and will get the expected error. Will add in the testfile as well.

2024-10-17 17:12 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/catalog.c
> +	user = get_user_for_database(old_db_name);
Right since we are using this function once we can include it itself in the below if condition after sysadmin which will avoid extra check.

2024-10-17 17:12 UTC, anju15bharti commented on contrib/babelfishpg_tsql/sql/ownership.sql
> +	EXECUTE format('GRANT CONNECT ON DATABASE %s TO dbcreator WITH GRANT OPTION', CURRENT_DATABASE());
yes the rebased commit will have those changes from securityadmin PR.

2024-10-18 11:14 UTC, anju15bharti commented on contrib/babelfishpg_tsql/sql/ownership.sql
> +	EXECUTE format('GRANT CONNECT ON DATABASE %s TO dbcreator WITH GRANT OPTION', CURRENT_DATABASE());
regarding any need giving dbcreator any permission from PG perspective, In that way we also don't need to give any permission to sysadmin but we decided to give it. So following that dbcreator and securityadmin role was given the required attribute.

2024-10-21 15:26 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							appendStringInfo(&query, "ALTER ROLE dummy WITH nocreaterole; ");
We can separate this out into another function to make it more readable, but maintaining counter to figure out which attribute to revoke will actually not be that useful here because We still need to separately grant and revoke priv from role for sysadmin, securityadmin and dbcreator because in general we cannot say through which membership we got this attribute. For example if the command it to drop member from sysadmin and we got createdb attribut via dbcreator then although the counter for createdb will be 1 yet it is not supposed to be revoked.

Still improvised the function using counter.

2024-10-21 15:26 UTC, anju15bharti commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--4.3.0--4.4.0.sql
> +
yes

2024-10-22 08:58 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/sql/ownership.sql
> +	EXECUTE format('GRANT CONNECT ON DATABASE %s TO dbcreator WITH GRANT OPTION', CURRENT_DATABASE());
So just for consistency.

2024-10-22 09:20 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							appendStringInfo(&query, "ALTER ROLE dummy WITH nocreaterole; ");
I was suggesting something similar to what you have already done for sysadmin.

Could you also move the increment counter conditions outside `if (IS_ROLENAME_SYSADMIN(rolename))`  this will allow all our revoke condition later on to look like
```else if (createdb == 1)``` only then revoke

2024-10-22 10:11 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							appendStringInfo(&query, "ALTER ROLE dummy WITH nocreaterole; ");
I don't think that would be a good idea because then irrespective of if the priv check is required for particular rolename or not we will always do the priv check for both securityadmin and dbcreator( which is actually not required) i.e in securityadmin case we need not to check for dbcreator priv and in dbcreator we need not to check for securityadmin priv.

So I think keeping the way it is would be more efficient.

2024-10-22 11:45 UTC, tanscorpio7 requested changes

2024-10-22 11:45 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +						|| !has_privs_of_role(GetSessionUserId(), get_dbcreator_oid())))
Can we reuse `IS_ROLENAME_SECURITYADMIN` and other macros here ? Also some other places we can reuse these macros.

2024-10-22 11:45 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +							!is_member_of_role(GetSessionUserId(), get_dbcreator_oid()))
Is this needed ? logins would already have the createdb privilege right ?

2024-10-22 11:45 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/catalog.c
> +	/* Check permission on the given database. */
Could we update the comment here to show db_creator can only alter the databases in which it has an active user.

2024-10-22 11:45 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/sql/upgrades/babelfishpg_tsql--4.3.0--4.4.0.sql
> +		OR role = 'dbcreator' COLLATE sys.database_default THEN
role IN ( .., .., ..)

2024-10-22 11:45 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							appendStringInfo(&query, "ALTER ROLE dummy WITH nocreaterole; ");
makes sense, then I think we can remove the entire counter approach. Just doing it for sysadmin does not really work. 
We can think of something else later on to refactor this. May be completely remove the attribute grant/revoke and just rely on memberships checks everywhere.

2024-10-22 11:53 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							appendStringInfo(&query, "ALTER ROLE dummy WITH nocreaterole; ");
No I think we can keep it for now since this counter is helping improving the checks call for sysadmin for every role case otherwise we will have to wrtie sysadmin priv check in each case. Better than just doing every priv check separately.

2024-10-22 12:51 UTC, HarshLunagariya requested changes

2024-10-22 12:51 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/sql/babelfishpg_tsql.sql
> +		OR role = 'dbcreator' COLLATE sys.database_default THEN
Refactor it to `role in (r1, r2, r2);`

2024-10-22 12:51 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/catalog.c
> +	/* Check permission on the given database. */
+1, instead of "active" , let's say "mapped" user.

2024-10-22 12:51 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +		new_record_login_ext[LOGIN_EXT_TYPE] = CStringGetTextDatum("R");
Can we use macro IS_BBF_FIXED_SERVER_ROLE here to combine 2 else if condition for secadmin and dbcreator?

2024-10-22 12:51 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +static void
We refactor it in following way for better readability:
```
static void 
gen_command_grant_revoke_priv_to_role(StringInfo query, const char *rolename,
							bool is_grant, Oid login_oid)
{
    int createrole = 0, createdb = 0;

	if (has_privs_of_role(login_oid, get_sysadmin_oid()))
	{
		createrole++;
		createdb++;
	}
	if (has_privs_of_role(login_oid, get_securityadmin_oid()))
	{
		createrole++;
	}
	if (has_privs_of_role(login_oid, get_dbcreator_oid()))
	{
		createdb++;
	}

	/* If sysadmin, provide attribute for role and database priv */
	if (IS_ROLENAME_SYSADMIN(rolename))
	{
		createrole += ((is_grant) ? 1 : -1);
		createdb += ((is_grant) ? 1 : -1);
	}
	else if (IS_ROLENAME_SECURITYADMIN(rolename))
	{
		createrole += ((is_grant) ? 1 : -1);
	}
	else if (IS_ROLENAME_DBCREATOR(rolename))
	{
		createdb += ((is_grant) ? 1 : -1);
	}
	else
	{
		....
	}
	
	appendStringInfo(query, "ALTER ROLE dummy WITH %s %s; ", (createdb > 0) ? "nocreatedb" : "createdb", (createrole > 0) ? "nocreaterole" : "createrole");
}
```

2024-10-22 12:51 UTC, HarshLunagariya commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +
```
select is_srvrolemember('sysadmin', 'dbcreator')
select is_srvrolemember('securityadmin', 'dbcreator')
And vice versa tests.
```

2024-10-22 12:51 UTC, HarshLunagariya commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +GO
Just double-checking, This is verified ideal T-SQL behaviour, right?

2024-10-22 12:54 UTC, HarshLunagariya commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +
+ Please add testcases for sp_helpsrvrole and sp_helpsrvrolemember

2024-10-22 12:55 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +static void
But then it will unnecessarily call the priv check for securityadmin in case of dbcreator and priv check for dbcreator in case of securityadmin which doesn't seem efficient. Does it?

2024-10-22 13:02 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +static void
The 2nd and 3rd execution of `has_privs_of_role()`(internally uses `roles_is_member_of`)  will be quick, because internally it caches the member's list (based on the given role's oid) after 1st execution. So, efficiency shouldn't be issue here.

2024-10-22 16:28 UTC, Deepesh125 commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +	dbcreator = get_role_oid(BABELFISH_DBCREATOR, true);  /* missing OK */
why missing_ok = true? we are not validating dbcreator before checking membership on line 963

2024-10-22 16:28 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/catalog.h
> +	IS_ROLENAME_DBCREATOR(rolename))
its really hard to understand distinction b/w what is defined here vs IS_DEFAULT_BBF_SERVER_ROLE defined at tds_int.h

2024-10-22 16:28 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +		new_record_login_ext[LOGIN_EXT_TYPE] = CStringGetTextDatum("R");
+1

2024-10-22 16:28 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +						|| !has_privs_of_role(GetSessionUserId(), get_dbcreator_oid())))
update comment also

2024-10-23 05:52 UTC, Deepesh125 commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +~~END~~
this is expected?

2024-10-23 07:03 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/catalog.h
> +	IS_ROLENAME_DBCREATOR(rolename))
`IS_DEFAULT_BBF_SERVER_ROLE` includes our internal bbf role bbf_role_admin as well while other one is just for our supported fixed server role.

2024-10-23 07:07 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +							!is_member_of_role(GetSessionUserId(), get_dbcreator_oid()))
We should keep it as earlier we were making sure that it's sysadmin by checking if it can set sysadmin role, so better to keep this check. Also There can be possibility that login(malicious) is not member of any of the roles but has creatdb priv somehow from pg endpoint.

2024-10-24 06:47 UTC, anju15bharti commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +GO
yes

2024-10-24 07:02 UTC, tanscorpio7 commented on contrib/babelfishpg_tds/src/backend/tds/tdsutils.c
> +	dbcreator = get_role_oid(BABELFISH_DBCREATOR, true);  /* missing OK */
I plan on completely refactoring this code area as part of BABEL-5332

2024-10-24 09:05 UTC, anju15bharti commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +
sp_helpsrvrole is unsupported and added test for sp_helpsrvrolemember.

2024-10-24 09:35 UTC, tanscorpio7 requested changes

2024-10-24 09:35 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	datdba = get_role_oid("sysadmin", false);
lets use `get_sysadmin_oid`

2024-10-24 09:35 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +			|| has_privs_of_role(roleid, get_dbcreator_oid()) || login_is_db_owner))
Lets also check for createdb privilege since that is what we do during create db.

2024-10-24 09:35 UTC, tanscorpio7 commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +-- tsql
Couple of negative cases we can test.
1. db_creator creates database -> transfer ownership to someone else -> cannot do any action insdie database i.e. does not map to dbo.
2. Create databases using dbcreator and sysadmin. remove the login from dbcreator and then check if restricted actions. alter/drop on existing dbs.

2024-10-24 09:55 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +			|| has_privs_of_role(roleid, get_dbcreator_oid()) || login_is_db_owner))
`has_prive_of_role` makes sure that. So need not to check for createdb priv.

2024-10-24 09:59 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +			|| has_privs_of_role(roleid, get_dbcreator_oid()) || login_is_db_owner))
My point was this should look same as the check we do in create database plus the OR with login_is_db_owner.

2024-10-24 10:08 UTC, anju15bharti commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +-- tsql
1. when we transfer the ownership through alter authorization, ownership gets revoked from previous login which will be the same case there and hence it will become normal case where it will be able to drop database but not alter until it has mapped user for that database. will add testcases as well.
2. We already have check that ensure that if login is member of both dbcreator and sysadmin, removed login from dbcreator it will still have attribute priv through sysadmin membership (ref: test/JDBC/expected/dbcreator_role-vu-verify.out:253)

2024-10-24 13:19 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +				((grant_createrole) ? "createrole" : ((revoke_createrole) ? "nocreaterole" : "nocreatedb")));
One more suggestion:
```suggestion
	appendStringInfo(query, "ALTER ROLE dummy WITH %s %s; ", grant_createrole ? "createrole" : (revoke_createrole ? "nocreaterole" : ""),
															 grant_createdb ? "createdb" : (revoke_createdb ? "nocreatedb" : ""));
```

2024-10-24 13:19 UTC, HarshLunagariya commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +~~ERROR (Message: The server principal "dbcreator_login1" is not able to access the database "dbcreator_db1" under the current security context)~~
Can you please explain this case? What are we trying to test?

2024-10-24 13:21 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +			|| has_privs_of_role(roleid, get_dbcreator_oid()) || login_is_db_owner))
We don't have a strong reason to/not rely on createdb privileges. My suggestion is to stick with existing check without createdb priv check.

2024-10-24 13:40 UTC, anju15bharti commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +~~ERROR (Message: The server principal "dbcreator_login1" is not able to access the database "dbcreator_db1" under the current security context)~~
It's a negative case that if dbcreator login don't have mapped user in the database, it should disconnect and should not get mapped to dbo by any chance.

2024-10-24 15:49 UTC, HarshLunagariya commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +~~ERROR (Message: The server principal "dbcreator_login1" is not able to access the database "dbcreator_db1" under the current security context)~~
Alright, Got it.

2024-10-24 16:03 UTC, anju15bharti commented on test/JDBC/expected/dbcreator_role-vu-verify.out
> +~~END~~
yes, since this login has created the database `dbcreator_db`

2024-10-25 05:35 UTC, tanscorpio7 approved these changes

2024-10-25 05:35 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +		is_securityadmin = 2;
lets use true and false for bools

2024-10-25 05:35 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +							!is_member_of_role(GetSessionUserId(), get_dbcreator_oid()))
can we use `has_privs_of_role` instead of `is_member_of_role` since that is what we used everywhere else.

2024-10-25 10:41 UTC, HarshLunagariya approved these changes

2024-10-25 11:00 UTC, merged