Support db_datareader/db_datawriter
amazon-aurora/babelfish_extensions pull request #68
Opened 2024-10-19 19:38 UTC by shalinilohia50

### Description
Implement database roles `db_datareader` and `db_datawriter` 

* Members of the db_datareader fixed database role can read all data from all user tables and views. User objects can exist in any schema except sys and INFORMATION_SCHEMA.
* Members of the db_datawriter fixed database role can add, delete, or change data in all user tables. In most use cases, this role is combined with db_datareader membership to allow reading the data that is to be modified.

Engine PR: https://github.com/amazon-aurora/postgresql_modified_for_babelfish/pull/98

### Issues Resolved
Task: [BABEL-3883](https://jira.rds.a2z.com/browse/BABEL-3883)
Signed-off-by: Shalini Lohia <lshalini@amazon.com>

### Test Scenarios Covered ###
Test Plan: https://quip-amazon.com/xZyQABuVCz9u/Test-Plan-for-database-roles 
* **Use case based -** Added

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-21 04:32 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	appendStringInfo(&query, "DROP ROLE dummy; ");
Should we execute DROP OWNED BY? Will it be able to help cleaning up default privileges on these roles?

2024-10-21 04:32 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +										errmsg("Cannot grant, deny or revoke permissions to or from special roles.")));
Can we refactor this? It is duplicated at 3 places. And does it make sense to add a check for all the fixed db roles?

2024-10-21 04:32 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +		!has_privs_of_role(GetSessionUserId(),get_role_oid(db_owner_name, false)))
Only db_owner membership check on current_user should be sufficient. I'm not sure in existing why are we relying on the session user for add/dropping the membership of database roles.

2024-10-21 06:44 UTC, anju15bharti requested changes

2024-10-21 06:44 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	}
Can we refactor it to make a common function for database_roles to throw this error? Because it seems redundant.

2024-10-21 06:44 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +										errmsg("Cannot grant, deny or revoke permissions to or from special roles.")));
+1

2024-10-21 06:44 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +		SetUserIdAndSecContext(get_bbf_role_admin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
here as well we are setting our internal role, shouldn't it also escalate the priv here? @HarshLunagariya

2024-10-21 06:44 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +		!has_privs_of_role(GetSessionUserId(),get_role_oid(db_owner_name, false)))
+1

2024-10-21 06:44 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	db_datawriter = get_db_datawriter_name(dbname);
Why have we casted it to const char* in many other places as well?

2024-10-21 06:44 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	pfree(query.data);
Why are we only pfreeing query.data and not query because we will always initialize the query with memory allocation in `initStringInfo`?

2024-10-21 06:44 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +				const char	*db_datawriter = get_db_datawriter_name(dbname);
+1 , shouldn't we define these with char instead of const char* anf pfree it as well since in `get_db_datareader_name` and `get_db_datawriter_name` we are allocating the memory?

2024-10-21 06:44 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +	initStringInfo(&query);
we should pfree `query` as well.

2024-10-21 08:41 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	appendStringInfo(&query, "DROP ROLE dummy; ");
Do we really need this? 
Adding DROP OWNED BY doesn't change the behavior but affects the pg_dump tests and throwing error:
```
 DROP DATABASE IF EXISTS babel_2170_db1;
 GO
+~~ERROR (Code: 33557097)~~
+
+~~ERROR (Message: permission denied to drop objects)~~
```

2024-10-22 06:03 UTC, rishabhtanwar29 approved these changes

2024-10-22 15:09 UTC, HarshLunagariya requested changes

2024-10-22 15:09 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	appendStringInfo(&query, "DROP ROLE dummy; ");
What is it trying to drop?

2024-10-22 15:09 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +}
Shouldn't this be applicable to all the fixed db roles? In that case we can directly use the existing MACRO. so that everytime we won't need to change this function.

2024-10-22 15:09 UTC, HarshLunagariya commented on test/JDBC/expected/BABEL-CHECK-CONSTRAINT-vu-prepare.out
> +GO
Why this change?

2024-10-22 15:09 UTC, HarshLunagariya commented on test/JDBC/input/test_windows_login-vu-prepare.mix
> +-- sla 70000
Was it consistently failing? We should try to investigate the perf. degrade reasons.

2024-10-22 15:09 UTC, HarshLunagariya commented on test/JDBC/input/BABEL-SP_COLUMN_PRIVILEGES.mix
> +-- sla_for_parallel_query_enforced 50000
Was it consistently failing? We should try to investigate the perf. degrade reasons.

2024-10-22 15:09 UTC, HarshLunagariya commented on test/JDBC/expected/datareader_datawriter-vu-verify.out
> +-- bbf dump does not dump password so reset the password
is_member() and is_rolemember() test case should be part for upgrade test file.

+ Normal testcases to validate whether any other fixed role is not member of these roles.

2024-10-22 15:09 UTC, HarshLunagariya commented on test/JDBC/expected/datareader_datawriter.out
> +~~END~~
Shouldn't it be 0?

2024-10-22 15:09 UTC, HarshLunagariya commented on test/JDBC/expected/datareader_datawriter.out
> +
Can we refactor the test - to test positive/negative cases only when current user is only member of either db_datareader and db_datawriter? Currently, in all cases it is either member of both or none.

2024-10-22 15:09 UTC, HarshLunagariya commented on test/JDBC/expected/datareader_datawriter.out
> +GO
Can we please add testcases for following system procs?
    * sp_helpdbfixedrole testcase -- I think this got covered in existing test cases
    * sp_helpuser
    * sp_helprole
    * sp_helprolemember

2024-10-22 16:06 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	appendStringInfo(&query, "DROP ROLE dummy; ");
Here we are dropping the db_datareader and db_datawriter roles. 
If there had to be any dependent privilege, then DROP ROLE <> wouldn't have been successful. Do we need DROP OWNED BY in that case?

2024-10-23 05:33 UTC, shalinilohia50 commented on test/JDBC/expected/BABEL-CHECK-CONSTRAINT-vu-prepare.out
> +GO
We created this table from the PG endpoint before upgrade. We execute some GRANTs and ALTER DEFAULT PRIVILEGES statements and to have that privilege on this particular object, we have to grant permission to master_dbo else we get permission denied while upgrade.

2024-10-23 14:41 UTC, HarshLunagariya commented on test/JDBC/expected/BABEL-CHECK-CONSTRAINT-vu-prepare.out
> +GO
Does it break upgrade?

2024-10-23 14:50 UTC, shalinilohia50 commented on test/JDBC/expected/BABEL-CHECK-CONSTRAINT-vu-prepare.out
> +GO
Yes, because during upgrade we execute those GRANT statements and that give permission denied on this object since this table is created in BBF schema via PG endpoint.

2024-10-23 15:48 UTC, HarshLunagariya reviewed
Overall changes looks good to me!, Just one testcase addition for is_rolemember() is required as discussed offline.

2024-10-23 15:55 UTC, shalinilohia50 commented
> Overall changes looks good to me!, Just one testcase addition for is_rolemember() is required as discussed offline.

Missed mentioning it earlier, that test case is already added in the `datareader_datawriter-vu-verify.mix` test file.

2024-10-23 16:23 UTC, HarshLunagariya approved these changes

2024-10-23 17:11 UTC, merged

2024-10-25 16:16 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	appendStringInfo(&query, "DROP ROLE dummy; ");
Why do we not use `DROP ROLE rolename CASCADE` instead ? We are anyway dropping the objects, why do it in two steps.