Support db_securityadmin
amazon-aurora/babelfish_extensions pull request #70
Opened 2024-10-20 19:29 UTC by HarshLunagariya

[TBA]

2024-10-22 12:24 UTC, tanscorpio7 requested changes

2024-10-22 12:24 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +				pfree(nspname);
pfree nspname in else block ?

2024-10-22 12:24 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +								  get_role_oid(get_db_securityadmin_role_name(get_cur_db_name()), false)))
get_curr_db_name() needs to be freed, should we use `get_current_pltsql_db_name`

2024-10-22 12:24 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							(isrole && has_privs_of_role(GetUserId(), get_role_oid(db_securityadmin_role, false))))
Should we create a helper to get db_security admin role OID ?

2024-10-22 12:24 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	add_to_bbf_authid_user_ext(db_securityadmin, DB_SECURITYADMIN, dbname, NULL, NULL, true, true, false);
has_dbaccess should be false ? or does this role also grant connect privilege.

2024-10-22 14:04 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +	if (!IS_TDS_CLIENT() || sql_dialect != SQL_DIALECT_TSQL)
IS_TDS_CLIENT is defined as 
```
#define IS_TDS_CLIENT() (*pltsql_protocol_plugin_ptr && \
						 (*pltsql_protocol_plugin_ptr)->is_tds_client)
```
we should use port->is_tds_conn now

2024-10-22 14:04 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_COLUMN:
what about view or materialised view?

2024-10-22 14:04 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_TYPE:
Interesting! what kind of privilege could it have? and example/test case will help understand it better

2024-10-22 14:04 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_ROUTINE:
whats difference from func/proc?

2024-10-22 14:04 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/multidb.c
> +	truncate_identifier(name, strlen(name), false);
do we also truncate securityadmin for statement like grant/revoke and for procedure sp_addrolemember

2024-10-22 14:04 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/multidb.c
> +	truncate_identifier(name, strlen(name), false);
Please point me the test cases for this change

2024-10-22 14:06 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	db_securityadmin = get_db_securityadmin_role_name(dbname);
pfree?

2024-10-22 15:07 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							(isrole && has_privs_of_role(GetUserId(), get_role_oid(db_securityadmin_role, false))))
+1

2024-10-23 07:50 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +				pfree(nspname);
Addressed.

2024-10-23 07:51 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +								  get_role_oid(get_db_securityadmin_role_name(get_cur_db_name()), false)))
Addressed.

2024-10-23 07:53 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_COLUMN:
It's missing -- will add it, Just wondering how the view test case is working? Maybe it is getting the privileges via column privilege logic.

2024-10-23 07:56 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +	if (!IS_TDS_CLIENT() || sql_dialect != SQL_DIALECT_TSQL)
Done.

2024-10-23 07:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_TYPE:
Currently, we don't support GRANT/REVOKE any type privileges. So we won't need it. We will only need if somewhere internally we grant some type permissions in case of tvp, table-valued functions etc. Need to add tests around that to confirm.

2024-10-23 08:16 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	db_securityadmin = get_db_securityadmin_role_name(dbname);
Done, in all relevant APIs.

2024-10-24 08:48 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	add_to_bbf_authid_user_ext(db_securityadmin, DB_SECURITYADMIN, dbname, NULL, NULL, true, true, false);
No, it's doesn't grant connect privilege. Updated.

2024-10-24 08:53 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							(isrole && has_privs_of_role(GetUserId(), get_role_oid(db_securityadmin_role, false))))
Done.

2024-10-24 08:54 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/multidb.c
> +	truncate_identifier(name, strlen(name), false);
Not covered in existing tests, Adding those.

2024-10-24 11:01 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_ROUTINE:
[PG documentation](https://www.postgresql.org/docs/current/xproc.html#:~:text=Collectively%2C%20functions%20and%20procedures%20are%20also%20known%20as%20routines.%20There%20are%20commands%20such%20as%20ALTER%20ROUTINE%20and%20DROP%20ROUTINE%20that%20can%20operate%20on%20functions%20and%20procedures%20without%20having%20to%20know%20which%20kind%20it%20is.%20Note%2C%20however%2C%20that%20there%20is%20no%20CREATE%20ROUTINE%20command.)

> Collectively, functions and procedures are also known as routines. There are commands such as [ALTER ROUTINE](https://www.postgresql.org/docs/current/sql-alterroutine.html) and [DROP ROUTINE](https://www.postgresql.org/docs/current/sql-droproutine.html) that can operate on functions and procedures without having to know which kind it is. Note, however, that there is no CREATE ROUTINE command.

2024-10-24 11:01 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +	if (!IS_TDS_CLIENT() || sql_dialect != SQL_DIALECT_TSQL)
Off topic, should we change `IS_TDS_CLIENT` to use port->is_tds_conn

2024-10-24 11:08 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_ROUTINE:
Anyways, I'm trimming down on these object type which are not required.

2024-10-24 11:15 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_COLUMN:
objType is set in parser and grant stmt uses the same syntax for views and tables, so views fall under table obj type.
I think we can match the list against [ExecGrantStmt_oids](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/4f6fa60f2f4465e0713f01667af667cd33bf8a7b/src/backend/catalog/aclchk.c#L593) to see if we covered everything.

2024-10-24 11:25 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_COLUMN:
@tanscorpio7 Thanks for pointing it. Unknowingly, I have done that only. But I think there is not harm including those extra object types.

2024-10-24 11:40 UTC, tanscorpio7 requested changes

2024-10-24 11:40 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	update_DropOwnedStmt(stmt, list_make4(pstrdup(db_securityadmin), pstrdup(db_accessadmin), pstrdup(db_owner), pstrdup(dbo)));
Why isn't datareader and writer not here ?

2024-10-24 11:40 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +static void handle_grantstmt_for_dbsecadmin(ObjectType objType, Oid objId, Oid ownerId, AclMode privileges, Oid *grantorId, AclMode *grantOptions);
Would this be more suited under `Object Access Hook`.

Also lets add some comments in utility hook under GRANTSTMT that indicates there is some lower level handling for members of dbsecadmin for this command type.

2024-10-24 11:40 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +								  get_role_oid(get_db_securityadmin_role_name(get_current_pltsql_db_name()), false)))
Would it be better to add these checks at beginning of the function ?
quick exit 
-> if dialect not tsql 
-> if already have the privs
-> if not member of dbsecadmin
So that this code gets triggered as less as possible.

2024-10-24 11:40 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_COLUMN:
I think it may be better to not add those since we cannot add tests for it.

2024-10-24 11:46 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +								  get_role_oid(get_db_securityadmin_role_name(get_current_pltsql_db_name()), false)))
Also lets add some comments for this function

2024-10-24 15:55 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	update_DropOwnedStmt(stmt, list_make4(pstrdup(db_securityadmin), pstrdup(db_accessadmin), pstrdup(db_owner), pstrdup(dbo)));
+ Adding @shalinilohia50 here for better context

2024-10-24 20:31 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +								  get_role_oid(get_db_securityadmin_role_name(get_current_pltsql_db_name()), false)))
Done

2024-10-25 05:57 UTC, shalinilohia50 commented on test/JDBC/expected/db_securityadmin-vu-verify.out
> +CREATE SCHEMA babel_5135_sch1;
Who will be the owner of schema in this case? dbo?

2024-10-25 06:05 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +		    strcmp(user_name, db_datareader) != 0 &&
Nit: Indentation.

2024-10-25 06:07 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	appendStringInfo(&query, "DROP OWNED BY dummy, dummy, dummy, dummy CASCADE; ");
Do we really need this `DROP OWNED BY db_securityadmin`?
IIUC, the dependent objects should be correctly cleaned up by executing `DROP OWNED BY dbo, dbo_owner`.

2024-10-25 06:07 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +		    strcmp(user_name, db_datareader) != 0 &&
Nit: Indentation

2024-10-25 06:11 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	update_DropOwnedStmt(stmt, list_make4(pstrdup(db_securityadmin), pstrdup(db_accessadmin), pstrdup(db_owner), pstrdup(dbo)));
Do we really need this `DROP OWNED BY db_securityadmin/ db_accessadmin`?

The dependent objects should be correctly cleaned up by executing `DROP OWNED BY dbo, dbo_owner`.
There was no need to add `db_datareader` and `db_datawriter` here because of the fact that the objects like role/user that could have been dependent on these database roles were getting dropped already using the above statement.

2024-10-25 09:18 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +	if (!IS_TDS_CLIENT() || sql_dialect != SQL_DIALECT_TSQL)
Yes, we generally should fix that but not with this PR. @tanscorpio7 could you please open jira for that? we need to evaluate why is current check making use of (*pltsql_protocol_plugin_ptr)->is_tds_client and what challenges we may face if we use tds_conn?

2024-10-25 09:22 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		case OBJECT_COLUMN:
+1

2024-10-25 10:51 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/multidb.c
> +	truncate_identifier(name, strlen(name), false);
Apart from that, I think we can save some calls to truncate_identifier if we can cache db_securityadmin rolname for given db

2024-10-25 13:33 UTC, tanscorpio7 requested changes

2024-10-25 13:33 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +						Oid			db_securityadmin = get_role_oid(get_db_securityadmin_role_name(db_name), false);
`get_db_securityadmin_oid` here and some other places.

2024-10-25 13:33 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +			!is_schema_from_db(schema_oid, get_cur_db_id()))
Doesnt `is_schema_from_db(schema_oid, get_cur_db_id()`  condition make the other two redundant ?

2024-10-29 20:32 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	update_DropOwnedStmt(stmt, list_make4(pstrdup(db_securityadmin), pstrdup(db_accessadmin), pstrdup(db_owner), pstrdup(dbo)));
Database cleanup should not be blocked because of these internal roles's object dependency. So, we have added this for sanity check.

2024-10-29 20:33 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	appendStringInfo(&query, "DROP OWNED BY dummy, dummy, dummy, dummy CASCADE; ");
It just be on the safer side and not to block the database cleanup due to it.

2024-10-29 20:34 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +			!is_schema_from_db(schema_oid, get_cur_db_id()))
Addressed.

2024-10-29 20:38 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +		    strcmp(user_name, db_datareader) != 0 &&
Addressed.

2024-10-29 20:39 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +		    strcmp(user_name, db_datareader) != 0 &&
Addressed.

2024-10-29 20:49 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +static void handle_grantstmt_for_dbsecadmin(ObjectType objType, Oid objId, Oid ownerId, AclMode privileges, Oid *grantorId, AclMode *grantOptions);
Would this be more suited to declare under Object Access Hook comment --> No, I think it is better placed under utility only.

Added comments in GRANT stmt handling in bbf_Processutility code.

2024-10-29 20:50 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +						Oid			db_securityadmin = get_role_oid(get_db_securityadmin_role_name(db_name), false);
Done

2024-10-29 21:09 UTC, HarshLunagariya commented on test/JDBC/expected/db_securityadmin-vu-verify.out
> +CREATE SCHEMA babel_5135_sch1;
1. current_user, Added the query where we are validating the schema owner.
2. Yes for both sub-questions. Added the test case for the same.

2024-10-30 10:39 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	pfree((char *) dbo);
Should we define all these variables as (char *) instead of (const char *)?

2024-10-30 10:39 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	char		   *db_securityadmin;
Nit: Indentation

2024-10-30 10:46 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		if (!is_schema_from_db(schema_oid, get_cur_db_id()))
Does this check handle shared schema as well?

2024-10-30 12:08 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	pfree((char *) dbo);
Keeping it same for now since it's an improvement but not affect the operations.

2024-10-30 12:09 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +		if (!is_schema_from_db(schema_oid, get_cur_db_id()))
It will return false.

2024-10-31 10:44 UTC, merged