Support fixed database role db_ddlaccessadmin
amazon-aurora/babelfish_extensions pull request #71
Opened 2024-10-21 18:31 UTC by tanscorpio7

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-04 06:30 UTC, HarshLunagariya requested changes

2024-11-04 06:30 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +	Assert(list_length(stmt_list) == 4);
Why this change? The same scenario with start crashing the server instead of throwing the error.
This can be possible when threat actor tries inject extra SQL statements and statement counts are more than expected stmts.

My opinion is to keep throwing error message only to avoid DOS possibilities by crashing the server.

2024-11-04 06:30 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pltsql.h
> +#define IS_TDS_CONN() (MyProcPort && MyProcPort->is_tds_conn)
I suggest adding comments about the usecases/restrictions/diff. of IS_TDS_CLIENT() & IS_TDS_CONN() ?
We can take guidance from @Deepesh125 or @KushaalShroff .

2024-11-04 06:30 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							CommandCounterIncrement();
Why is it needed now? Did we lack testcases which didn't catch it?

2024-11-04 06:30 UTC, HarshLunagariya commented on contrib/babelfishpg_common/src/collation.c
> +	{0x0450, 1251, PG_WIN1251, "mn_MN"}, //Mongolian:Mongolia
unwanted change

2024-11-04 06:30 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	while ((tuple = heap_getnext(tblscan, ForwardScanDirection)) != NULL)
Just wondering, Any reason to do it this way?

2024-11-04 06:30 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	Assert(list_length(stmt_list) == 7);
Should we throw the error? As discussed in earlier comments since it's better to error out than crashing the server.

2024-11-04 06:30 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +			nsp_owner = get_role_oid(dbo_name, false);
Are we using this hook for assigning owner while creating the schema? I don't think so, Just confirming.

2024-11-04 06:30 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +				has_privs_of_role(GetUserId(), db_ddladmin))
Let's use either has_privs_of_role() OR is_member_of_role().

2024-11-05 14:48 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	while ((tuple = heap_getnext(tblscan, ForwardScanDirection)) != NULL)
Just matching engine coding style.

2024-11-05 14:48 UTC, tanscorpio7 commented on contrib/babelfishpg_common/src/collation.c
> +	{0x0450, 1251, PG_WIN1251, "mn_MN"}, //Mongolian:Mongolia
removed

2024-11-05 14:57 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							CommandCounterIncrement();
No, the earlier logic in `exec_database_roles_subcmds` passed the schema owner as an argument and had some special handling inside `exec_database_roles_subcmds` to avoid database lookup for this case.

Adding `CommandCounterIncrement` here means we can remove the special handing in `exec_database_roles_subcmds`.

2024-11-05 15:04 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +	Assert(list_length(stmt_list) == 4);
Injection is not possible here at all since we are parsing the statements with "dummy" placeholder so the number of statements returned will always be constant for every run.

But I will revert this back to error since I don't have a good argument for changing this to Assert.

2024-11-05 15:06 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +			nsp_owner = get_role_oid(dbo_name, false);
No, this hook is limited to schema contained objects only.

2024-11-11 12:58 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/catalog.c
> +				SetUserIdAndSecContext(get_bbf_role_admin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
1. Granting as bbf_role_admin -- seems bit of exaggeration? Are there any better options -- object owner/ schema owner?
2. Any other way without privilege escalation?

2024-11-11 14:07 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +	appendStringInfo(&query, "ALTER DEFAULT PRIVILEGES FOR ROLE dummy, dummy GRANT EXECUTE ON ROUTINES TO PUBLIC; ");
These roles are specified as NULL below , we can go with this query.
```
appendStringInfo(&query, "ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON ROUTINES TO PUBLIC; ");
```

2024-11-12 08:08 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +				SetUserIdAndSecContext(get_sysadmin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
Any specific reason why are we setting sysadmin instead of bbf_role_admin?

2024-11-12 08:14 UTC, anju15bharti commented on contrib/babelfishpg_tsql/src/hooks.c
> +		exec_internal_grant_on_function(objectId);
Let's add one line comment mentioning need of this function as we have shifted this func from bbf_ProcessUtility to here removing comment referring this function.

2024-11-12 10:48 UTC, thephantomthief commented on .github/workflows/jdbc-tests-db-collation.yml
> -on: [push, pull_request]
This is temporary right? I'm guessing we are doing this to prevent the actions from running twice until we formally merge this to main repo.

2024-11-12 10:48 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/hooks.c
> +	/* Advance command counter so new tuple can be seen by validator */
I think this is unintended

2024-11-12 19:10 UTC, tanscorpio7 commented on .github/workflows/jdbc-tests-db-collation.yml
> -on: [push, pull_request]
Yes

2024-11-12 19:10 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +	/* Advance command counter so new tuple can be seen by validator */
uncommitted this change

2024-11-12 19:11 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		exec_internal_grant_on_function(objectId);
Please see wording above definition of `exec_internal_grant_on_function`, let me know if that works.

2024-11-12 19:15 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +				SetUserIdAndSecContext(get_sysadmin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
postgres 16 onwards grants are tightly bound to grantor.
A user can only revoke a grant if it is the grantor. Even super user cannot revoke a grant unless it is the grantor.

We use sysadmin here to make sure that grantor is always sysadmin.

If we set current user as `bbf_role_admin` then select_best_grantor() may pick either `bbf_role_admin` or `sysadmin` depending upon what the grant is. To avoid this, we switch to sysadmin.

2024-11-12 19:18 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +	appendStringInfo(&query, "ALTER DEFAULT PRIVILEGES FOR ROLE dummy, dummy GRANT EXECUTE ON ROUTINES TO PUBLIC; ");
I am actually setting the list of roles just after `update_AlterDefaultPrivilegesStmt`.
and `DefElem` "roles" is only present if we pass FOR ROLE clause here.

2024-11-12 19:20 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +				has_privs_of_role(GetUserId(), db_ddladmin))
done

2024-11-13 07:21 UTC, Deepesh125 requested changes

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/catalog.c
> +				SetUserIdAndSecContext(get_bbf_role_admin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
why are we doing this inside try block?

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/dbcmds.c
>  /* Grant permissions on all the existing objects to db_datareader/db_datawriter. */
update comment

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +			SetUserIdAndSecContext(get_bbf_role_admin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
we should be doing this outside of try block

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/dbcmds.c
>  		/* Grant permissions on all the schemas in a database to db_datareader/db_datawriter */
update comment

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +			SetUserIdAndSecContext(get_bbf_role_admin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
Can you also explain why are we switching to bbf_role_admin? because seems like we would have already set user id to either sysadmin or bbf_role_admin. Check caller of bbf_role_admin

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +				SetUserIdAndSecContext(get_sysadmin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
we anyway need to optimise this for loop because we are repeatedly setting user id. Is it possible to segregate parse list for grant statements?

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		ownerId = GetUserId();
can you please explain this?

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +	logical_schema_name = get_logical_schema_name(NameStr(nsptup->nspname), true);
why mising_ok = true?

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +	db_ddladmin = get_db_ddladmin_oid(get_current_pltsql_db_name(), false);
is get_current_pltsql_db_name diff than get_cur_db?

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/multidb.c
> +	return db_ddladmin_oid;
better to cache this?

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							exec_drop_bbf_role_subcmds(stmt);
please explain this change

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/pltsql.h
> +#define IS_TDS_CONN() (MyProcPort && MyProcPort->is_tds_conn)
Ideally, IS_TDS_CLIENT() should be update to use MyProcPort->is_tds_conn but not sure if it will cause any other issue

2024-11-13 07:21 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +exec_drop_bbf_role_subcmds(DropRoleStmt *drop_stmt)
plz add comment explaining functionality

2024-11-13 07:35 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/multidb.c
> +	return db_ddladmin_oid;
we will need to also store the dbid for which we are storing the cached Oid.
For simplicity we can skip it since this is only called in DDL code paths.

2024-11-13 07:35 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +	db_ddladmin = get_db_ddladmin_oid(get_current_pltsql_db_name(), false);
`get_current_pltsql_db_name` does not palloc the dbname and returns const char *

2024-11-13 07:37 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +	logical_schema_name = get_logical_schema_name(NameStr(nsptup->nspname), true);
If user is creating in a schema created from postgres endpoint and then creating some objects in it through TDS endpoint.
In this case we will not have a `logical_schema_name` so we keep missingok = true & skip our handling if `logical_schema_name` is NULL.

2024-11-13 14:48 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	Assert(list_length(stmt_list) == 7);
Done

2024-11-13 14:51 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pltsql.h
> +#define IS_TDS_CONN() (MyProcPort && MyProcPort->is_tds_conn)
They are the same, the only difference I could see is we set `MyProcPort->is_tds_conn` a bit later compared to `IS_TDS_CLIENT()` but that will only affect pre login phase.

2024-11-13 15:10 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +				SetUserIdAndSecContext(get_sysadmin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
removed this handling entirely and instead
revoked grant option from `bbf_role_admin` so it never gets picked during GRANT ON DATABASE stmts.

2024-11-14 05:54 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +			SetUserIdAndSecContext(get_bbf_role_admin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
Right, we do not need to set userid again, removed the try catch block.

2024-11-14 06:01 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							exec_drop_bbf_role_subcmds(stmt);
Removed this handling.
> Problem that required to make this change
Members of db_ddladmin create func/proc with schema owner as the new func/proc owner. So when we reach object access hook, we will not be able to execute the internal grants we run since current user does not have that privilege. To fix this, the earlier approach was to set a global default privileges for all babelfish database roles so that we would not need to run these grants post creation. But this approach failed because logical bbf dump restore was not able to dump the new global default privileges.

> How do we solve this now
Switch to proc owner when running internal grants during postgres create.

2024-11-14 06:02 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pltsql_utils.c
> +exec_drop_bbf_role_subcmds(DropRoleStmt *drop_stmt)
https://github.com/amazon-aurora/babelfish_extensions/pull/71#discussion_r1841612777

2024-11-14 06:02 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +							exec_drop_bbf_role_subcmds(stmt);
+ @HarshLunagariya

2024-11-14 06:11 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		ownerId = GetUserId();
Everywhere this hook is used, the owner is already determined and is guaranteed to be valid. But in case of relations I had to place the hook just before we set the owner in engine. see `DefineRelation`

>Why place hook before engine determines ownerId ?

For relations ownerId could already be pre determined. ex: Creating sequence for identity column in which case table owner will be the sequence owner. In these cases we do not want to call our hook.

2024-11-14 06:41 UTC, Deepesh125 commented on test/JDBC/expected/BABEL-2403.out
> +text#!#sys#!#name#!#{"Rule": "<database_name> in babelfish_authid_user_ext must also exist in babelfish_sysdatabases"}
why are we seeing this diff?

2024-11-14 07:10 UTC, tanscorpio7 commented on test/JDBC/expected/BABEL-2403.out
> +text#!#sys#!#name#!#{"Rule": "<database_name> in babelfish_authid_user_ext must also exist in babelfish_sysdatabases"}
This is output of 
```
-- Output passed rules
SELECT * FROM sys.babelfish_inconsistent_metadata(true);
GO
```
We get one new entry for the role we added * 3 built in databases = 3 entries

2024-11-14 07:10 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
>  		/* Grant permissions on all the schemas in a database to db_datareader/db_datawriter */
done

2024-11-14 07:10 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
>  /* Grant permissions on all the existing objects to db_datareader/db_datawriter. */
done

2024-11-14 07:15 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/catalog.c
> +				SetUserIdAndSecContext(get_bbf_role_admin_oid(), save_sec_context | SECURITY_LOCAL_USERID_CHANGE);
posting offline discussion here for reference.

Tanzeel Khan
  Yesterday at 12:41
>That will actually not make a difference but having it inside TRY is more safe.
If we keep it outside TRY and in future we mistakenly add something between SetUserIdAndSecContext and beginning of TRY then it will become a problem.

Dipesh Dhameliya
  Yesterday at 12:42
>I would prefer it outside of TRY block because TRY block will switch context

Tanzeel Khan
  Yesterday at 12:43
>TRY block will switch context
Do you mean sigsetjump ?

Dipesh Dhameliya
  Yesterday at 12:43
>yes

Tanzeel Khan
  Yesterday at 12:49
>That is a problem only if we set local stack variables in TRY and then try to use it in CATCH. I am looking at :point_down::skin-tone-4:
 
>*
 >* Note: if a local variable of the function containing PG_TRY is modified
 >* in the PG_TRY section and used in the PG_CATCH section, that variable
 >* must be declared "volatile" for POSIX compliance.  This is not mere
 >* pedantry; we have seen bugs from compilers improperly optimizing code
 >* away when such a variable was not marked.  Beware that gcc's -Wclobbered
 >* warnings are just about entirely useless for catching such oversights.
 >*

Dipesh Dhameliya
  Yesterday at 12:50
>FINALLY will also do context switch, right?

Tanzeel Khan
  Yesterday at 12:51
>Yes, but we are not setting any local function variables in TRY.

Harsh Lunagariya
  Yesterday at 12:54
>I don't think global static will be affected. To avoid local variable issue, We specifically do GetUserIdAndSecContext() outside of TRY().
:yes:
1

Dipesh Dhameliya
  Yesterday at 12:54
>are we doing same at the other places? exisiting places?

Tanzeel Khan
  Yesterday at 13:01
>Yes, for example under T_CreateRoleStmt in process utility hook

Dipesh Dhameliya
  Yesterday at 13:24
>ok

2024-11-14 10:50 UTC, shalinilohia50 commented on test/JDBC/input/fixed_roles/db_ddladmin-vu-verify.mix
> +DROP TYPE babel_5116_tabletype2_new_name
Why are we dropping these objects in verify and not in cleanup? Is there any specific reason?

2024-11-14 10:58 UTC, tanscorpio7 commented on test/JDBC/input/fixed_roles/db_ddladmin-vu-verify.mix
> +DROP TYPE babel_5116_tabletype2_new_name
These tests are validating if db_ddladmin member can execute drop commands.

2024-11-14 13:26 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/hooks.c
> +	logical_schema_name = get_logical_schema_name(NameStr(nsptup->nspname), true);
how can this be possible? can you add example for the reference?

2024-11-14 13:27 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/multidb.c
> +	return db_ddladmin_oid;
we can reset cached value when `use db`command occurs

2024-11-14 13:29 UTC, Deepesh125 commented on test/JDBC/expected/BABEL-2403.out
> +text#!#sys#!#name#!#{"Rule": "<database_name> in babelfish_authid_user_ext must also exist in babelfish_sysdatabases"}
but aren't we creating physical role in the database? then why is it reporting incosistency?

2024-11-14 13:39 UTC, tanscorpio7 commented on test/JDBC/expected/BABEL-2403.out
> +text#!#sys#!#name#!#{"Rule": "<database_name> in babelfish_authid_user_ext must also exist in babelfish_sysdatabases"}
```
sys.babelfish_inconsistent_metadata(true);
```
Based on the function definition of `babelfish_inconsistent_metadata` it returns passed rules when true is passed as argument.

We also run this, which will return failed rules.
```
SELECT * FROM sys.babelfish_inconsistent_metadata();   <-- argument "return_consistency" defaults to false
```

2024-11-14 13:44 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +	logical_schema_name = get_logical_schema_name(NameStr(nsptup->nspname), true);
```
jdbc_testdb=# create schema master_s1 authorization master_dbo;
CREATE SCHEMA
```
User can run this from postgres endpoint ☝️  and then 👇  this will work from TDS endpoint
```
1> create table s1.t (id int)
2> go
```

We cannot allow this for db_ddladmin because we need to figure out if this schema belongs to current logical database which we cannot for schema created from psql endpoints.

2024-11-14 13:53 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/multidb.c
> +	return db_ddladmin_oid;
We will also need to handle other cases like rename_db and ensuring cache invalidation happens properly will be non-trivial.

2024-11-15 05:17 UTC, Deepesh125 commented on contrib/babelfishpg_tsql/src/multidb.c
> +	return db_ddladmin_oid;
Why? We have done similar thing for db collation. Not sure how would it be different here

2024-11-15 05:39 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/hooks.c
> +	/* Advance command counter so new tuple can be seen by validator */
misplaced comment

2024-11-15 05:39 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +	PG_END_TRY();
Improvement: Is there a possibility to push this logic(when it is ddladmin allow this validation ...) down to engine to avoid privilege escalation?

2024-11-15 05:39 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -
Why this change?

2024-11-15 05:39 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -			}
Why is this not required now?

2024-11-15 05:46 UTC, Deepesh125 approved these changes
Code changes LGTM

2024-11-15 06:16 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +	PG_END_TRY();
`CheckFunctionValidatorAccess` checks for EXECUTE privs on proc, we could add our hook there but doing here means we only allow pltsql lang routines.

2024-11-15 06:19 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -
Removed GRANT OPTION for CREATE ON DATABASE from bbf_role_admin, so. now it will not be picked as grantor

2024-11-15 06:19 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/dbcmds.c
> -			}
https://github.com/amazon-aurora/babelfish_extensions/pull/71#discussion_r1843239944

2024-11-15 09:14 UTC, HarshLunagariya commented on test/JDBC/expected/db_ddladmin-vu-prepare.out
> +CREATE TABLE babel_5116_t1 (id INT, con_col INT NOT NULL CONSTRAINT babel_5116_constr1 UNIQUE)
Remaining testcases:
1. Mandatory for merging:
 - ALTER TABLE ... ADD COLUMN ...
 - Temp Tables and Table variables
 - DDLs on database CREATE/DROP/ALTER database, ALTER AUTH. ON DATABASE

2. Can be added in separate PRs
 - Statement execution inside procedure
 - Operations on objects created after a user already has been granted membership in db_ddladmin
 - Operations on objects created by different users dbo, schema owner, etc.
 - Operations on schemas owned by someone other than dbo
 - system object testing
 - Testing restrictions from PG endpoint (It is being tracked as separate issue)

2024-11-15 09:14 UTC, HarshLunagariya commented on test/JDBC/expected/db_ddladmin-vu-verify.out
> +~~ERROR (Message: role "u" does not exist)~~
Improve this testcase `CREATE USER u FOR LOGIN babel_5116_l3`

2024-11-15 09:14 UTC, HarshLunagariya commented on test/JDBC/expected/db_ddladmin-vu-verify.out
> +~~ERROR (Message: role "babel_5116_l3" does not exist)~~
Improve this test case after creating babel_5116_l3 login

2024-11-15 09:14 UTC, HarshLunagariya commented on test/JDBC/expected/db_ddladmin-vu-verify.out
> +GO
This should have failed.

2024-11-19 07:40 UTC, merged