Support adding users to T-SQL db_owner database role
amazon-aurora/babelfish_extensions pull request #72
Opened 2024-11-05 11:30 UTC by thephantomthief

### Description

This commit adds support to alter the db_owner role and add/drop users from it.

Whenever a new user, say u1, is added to db_owner role, we will internally create a new role u1_obj which will be owner of all the objects of u1. By doing so, we are able to work around the cyclic dependency of role membership in postgres. If u1 creates new objects, using the pre-existing post object creation hook, we will reassign ownership of u1's objects to u1_obj.

Similarly, if u1 is dropped from db_owner role, we will drop the u1_obj role and reassign ownership u1's objects from u1_obj role back to u1.

Task: BABEL-4899
Signed-off-by: Sharu Goel <goelshar@amazon.com>

### Test Scenarios Covered ###
* **Use case based -** Yes

* **Boundary conditions -** N/A

* **Arbitrary inputs -** N/A

* **Negative test cases -** Yes

* **Minor version upgrade tests -** Yes

* **Major version upgrade tests -** Yes

* **Performance tests -** N/A

* **Tooling impact -** N/A

* **Client tests -** N/A

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-11-07 07:42 UTC, tanscorpio7 commented
Who will own schema if user runs
```
CREATE SCHEMA s1 AUTHORIZATION l1
```
and l1 is a member of db_owner. Will the internal role own the schema ?

2024-11-07 07:49 UTC, tanscorpio7 commented
The current grant on schema logic assumes only dbo and schema_owner can create objects in the schema.
Now any role which is a member of db_owner can create objects in any schema.

Question is will objects created by members of db_owner adhere to grants on schema ?
```
grant select on schema::s1 to l2
```
then as a member of db_owner create in that schema
```
create table s1.t (id int) <-- can l2 select on this ?
```

2024-11-07 08:36 UTC, tanscorpio7 requested changes

2024-11-07 08:36 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	if (sql_dialect != SQL_DIALECT_TSQL)
Should we also check if current connection is TDS CONN ?

2024-11-07 08:36 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +
We probably should have `CommandCounterIncrement();` here

2024-11-07 08:36 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +		change_object_owner_if_db_owner();
Since we are doing this way, we could add test cases for all the pg_catalog which contains some metadata related to ownerId and the newly created object.

For example when during create schema we record dependency on owner and default acls for the schema which also includes the ownerId, so we can add tests for both.

Not expecting to see any issues here, but would be good to have test cases. Thanks

2024-11-07 08:36 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/sql/ownership.sql
> +
Is there any possibility of merging this with `bbf_is_member_of_role_nosuper` ?

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	prev_current_user_id = GetSessionUserId();
Better naming would be prev_session_user_id

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +								create_bbf_authid_user_ext(stmt, isuser, isuser, from_windows);
We are only creating _obj role when adding any user as member of db_owner , right? Then should we have some kind of metadata just to rely on it to decide -  for which user, have we already created _obj_role and for which user, we haven't?

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +														queryEnv, dest, qc);
nit: Let's utilise - `call_prev_ProcessUtility()` here

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
>  							list_length(parsetree_list))));
Let's refactor this code to avoid duplication. Instead of 1/2 let's maintain a variable.

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +		return;
Shouldn't it be CurrentUser?

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +
Let's make sure we add testcases for long username and database name.

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +		appendStringInfo(&query, "DROP ROLE dummy; ");
Should we execute `DROP OWNED BY` statement here as well?

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> + * - If role is a member of db_owner, we will check if u1 is member of r1_obj role
> If role is a member of db_owner, we will check if u1 is member of r1_obj role
We need to test this thoroughly in terms of metadata visibility as well.

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	if (sql_dialect != SQL_DIALECT_TSQL)
+1

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	if (!is_member_of_role(role_oid, get_role_oid(get_db_owner_name(cur_db_name), true)))
missing ok is true here, is it expected?

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	appendStringInfoString(&query, "DROP ROLE dummy; ");
REASSIGN OWNED BY doesn't cover schema object?

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	rel = table_open(NamespaceRelationId, AccessShareLock);
RowExclusiveLock?

2024-11-13 18:59 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	rel = table_open(NamespaceRelationId, AccessShareLock);
RowExclusiveLock?

2024-11-14 07:38 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	if (sql_dialect != SQL_DIALECT_TSQL)
Added check for TDS connection

2024-11-14 07:38 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +
Done

2024-11-14 12:01 UTC, tanscorpio7 requested changes

2024-11-14 12:01 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +				ownerId = nsp_owner;
Let's skip this if current_user is dbo. For dbo we can fix it with BABEL-5361

2024-11-14 12:15 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/hooks.c
> +				ownerId = nsp_owner;
Done

2024-11-16 07:21 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +	prev_current_user_id = GetSessionUserId();
Done

2024-11-16 07:23 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +								create_bbf_authid_user_ext(stmt, isuser, isuser, from_windows);
As discussed offline, if member of db_owner is dropped from db_owner role or the member user is dropped from database, we will also drop the corresponding _obj role

2024-11-16 07:23 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +														queryEnv, dest, qc);
Done

2024-11-16 07:23 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
>  							list_length(parsetree_list))));
Done

2024-11-16 07:23 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +		return;
Done

2024-11-16 07:23 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +
Done

2024-11-16 07:26 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	if (!is_member_of_role(role_oid, get_role_oid(get_db_owner_name(cur_db_name), true)))
Made it false

2024-11-16 07:27 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	appendStringInfoString(&query, "DROP ROLE dummy; ");
It does, but I noticed an inconsistency where sometimes we will first attempt to transfer ownership of say a procedure before its schema which was causing this operation to fail inconsistently. To workaround this, I am explicitly transferring ownership of schemas first and then running REASSIGN OWNED BY

2024-11-16 07:28 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	rel = table_open(NamespaceRelationId, AccessShareLock);
For read-only catalog access, AccessShareLock should suffice right?

2024-11-16 11:10 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +		appendStringInfo(&query, "DROP ROLE dummy; ");
Done

2024-11-16 13:32 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/hooks.c
> + * We currently only do this if current user is member of db_ddladmin
```
We currently only do this if current user is member of db_ddladmin
```
This should be for db_owner as well, right?

2024-11-16 13:39 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +get_obj_role(const char *rolname)
We create a role "rolname_obj" when a rolename is added as a member of db_owner. 
Are we making sure that a User cannot create this "_obj" role on its own?

2024-11-16 13:51 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	rel = table_open(NamespaceRelationId, AccessShareLock);
Yes.

2024-11-16 13:51 UTC, shalinilohia50 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	rel = table_open(NamespaceRelationId, AccessShareLock);
It should be `AccessShareLock` for read only.

2024-11-16 14:50 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/hooks.c
> + * We currently only do this if current user is member of db_ddladmin
Yeah, actually I just copy pasted this from db_ddladmin to test if the same solution will work. My changes will be rebased over db_ddladmin commit so I will fix the comment when I'll get be resolving the conflicts.

2024-11-16 14:52 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +get_obj_role(const char *rolname)
We are not blocking it. There will be a limitation where if we already have say users u1_obj and u1, then end user won't be able to add u1 to db_owner role and we will throw an error. We had talked about this during design discussion and it was decided doing it like this is not really a big limitation

2024-11-19 05:13 UTC, shalinilohia50 approved these changes

2024-11-19 17:28 UTC, tanscorpio7 requested changes

2024-11-19 17:28 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	if (role_oid == dbo_id || dbo_id == InvalidOid || is_create_bbf_builtin_dbs)
Why is this flag needed, wouldn't we be in non tds connection when creating built in dbs ?

2024-11-19 17:28 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +		if (obj_rolname)
can this be null in some cases ?

2024-11-19 17:28 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	db_owner_id = get_role_oid(get_db_owner_name(get_cur_db_name()), false);
can we use `get_db_owner_oid`

2024-11-19 17:28 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/hooks.c
> +				&& user_oid != dbo_oid)
This should be `ownerId` instead of user_oid. Some places will have ownerId and `GetUserId()` different even in engine and lets move this check before has_privs_of_role for efficiency,

2024-11-19 17:28 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/multidb.c
> +				if ((strcmp(role_name, "db_owner") == 0) && get_db_principal_kind(get_role_oid(physical_principal_name, false), db_name) == BBF_ROLE)
MACRO for "db_owner" is defined.

2024-11-19 17:28 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +								create_bbf_authid_user_ext(stmt, isuser, isuser, from_windows);
MACRO for `(ALTER ROLE ADD )`

2024-11-19 17:28 UTC, tanscorpio7 commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +						if (has_privs_of_role(owner_oid, get_db_owner_oid(db_name, false)) && owner_oid != get_role_oid(get_dbo_role_name(db_name), false))
Let us have a helper for getting the dbo role oid given the db name. This will help reduce changes in multiple places.

2024-11-19 17:34 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	rel = table_open(NamespaceRelationId, AccessShareLock);
I was suggesting this because this row is being changed here -- We are changing the owner. Anyways, Engine API will anyway hold row ex. lock internally. so no worries to handle it here.

2024-11-19 17:36 UTC, HarshLunagariya reviewed
Code changes looks good. There are failures in some of workflows.

2024-11-20 05:51 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	if (role_oid == dbo_id || dbo_id == InvalidOid || is_create_bbf_builtin_dbs)
Yeah TDS_CONN check should suffice

2024-11-20 05:52 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +		if (obj_rolname)
No. Remove the if()

2024-11-20 05:52 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/rolecmds.c
> +	db_owner_id = get_role_oid(get_db_owner_name(get_cur_db_name()), false);
Yes. Done

2024-11-20 05:52 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/hooks.c
> +				&& user_oid != dbo_oid)
Done

2024-11-20 05:53 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/multidb.c
> +				if ((strcmp(role_name, "db_owner") == 0) && get_db_principal_kind(get_role_oid(physical_principal_name, false), db_name) == BBF_ROLE)
Replaced with DB_OWNER

2024-11-20 05:53 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +						if (has_privs_of_role(owner_oid, get_db_owner_oid(db_name, false)) && owner_oid != get_role_oid(get_dbo_role_name(db_name), false))
Done

2024-11-21 04:56 UTC, thephantomthief commented on contrib/babelfishpg_tsql/src/hooks.c
> +		change_object_owner_if_db_owner();
Added for more object types

2024-11-21 09:00 UTC, HarshLunagariya approved these changes

2024-11-21 09:00 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/dbcmds.c
> +		char 	   *original_user_name = get_authid_user_ext_original_name(user_name, dbname, true);
When do we get original_user_name NULL?

2024-11-21 09:00 UTC, HarshLunagariya commented on contrib/babelfishpg_tsql/src/pl_handler.c
> +								create_bbf_authid_user_ext(stmt, isuser, isuser, from_windows);
Let's track the effort somewhere to add this constraint that "if any user is member of db_owner then it should have _obj user created" in metadata consistency check.

2024-11-21 09:00 UTC, HarshLunagariya commented on test/JDBC/expected/db_owner-vu-verify.out
> +dbowner__main_db_dbowner__u1_obj
Have we tested `is_member('dbowner__main_db_dbowner__u1', 'dbo')` from ideal behaviour P.O.V. ?

2024-11-21 09:00 UTC, HarshLunagariya commented on test/JDBC/expected/db_owner-vu-verify.out
> +dbowner__main_db_dbowner__u1_obj
+ just double checking if we have existing case covering for sp_helpuser, sp_helprolemember,... etc procedures.
+ We need to test extended properties as well.

2024-11-21 10:03 UTC, tanscorpio7 approved these changes

2024-11-21 10:44 UTC, merged